/**
 * Shared auth schema configuration.
 * This file is the single source of truth for all schema-affecting config:
 * - Plugins
 * - User/session additionalFields
 * - Custom table/field names
 * - ID generation settings
 *
 * Used by both:
 * - auth.ts (CLI stub for schema generation)
 * - app/auth/auth.server.ts (runtime config)
 */
import { magicLink, admin } from "better-auth/plugins";

type MagicLinkSender = Parameters<typeof magicLink>[0]["sendMagicLink"];

type CreatePluginsParams = {
  sendMagicLink?: MagicLinkSender;
};

/**
 * Creates the plugins array with optional runtime implementations.
 * Add/remove plugins here - both CLI and runtime will stay in sync.
 */
export function createPlugins({ sendMagicLink }: CreatePluginsParams = {}) {
  return [
    magicLink({
      sendMagicLink: sendMagicLink ?? (async () => {}),
    }),
    admin(),
  ];
}

/**
 * Custom fields added to the user table.
 * These are generated by the CLI and available at runtime.
 */
export const userAdditionalFields = {
  // Example:
  // role: {
  //   type: "string",
  //   required: false,
  //   defaultValue: "user",
  //   input: false,
  // },
} as const;

/**
 * Custom fields added to the session table.
 */
export const sessionAdditionalFields = {
  // Example:
  // deviceId: {
  //   type: "string",
  //   required: false,
  // },
} as const;

/**
 * Custom table/field name mappings.
 * Uncomment and modify if you need different names than defaults.
 */
// export const userModelConfig = {
//   modelName: "users",
//   fields: {
//     email: "email_address",
//   },
// };

// export const sessionModelConfig = {
//   modelName: "sessions",
// };
